# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- name: a
  value: 1
- name: b
  value: 2

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: My first stage
    jobs:
      - job:
        displayName: My first job
        steps:
          - script: |
              Sum=$((${{ variables.a }}+${{ variables.b }}))
              echo "${{ variables.a }}">sum_script.txt
              echo "${{ variables.b }}">>sum_script.txt
              echo $Sum>>>sum_script.txt
            displayName: 'Write sum in file'

          - publish: sum_script.txt
            displayName: 'Publish artifact'
